;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Audi.2D.test",DevComment="")
+GameplayTagList=(Tag="Audio.2D.Test",DevComment="")
+GameplayTagList=(Tag="Audio.3D.Test",DevComment="")
+GameplayTagList=(Tag="Audio.3D.TestYoutube",DevComment="")
+GameplayTagList=(Tag="Test2D",DevComment="")
+GameplayTagList=(Tag="TestYoutube",DevComment="")
+GameplayTagList=(Tag="Category.Deco",DevComment="Primary Category Deco")
+GameplayTagList=(Tag="Category.Deco.Furniture",DevComment="SubCategory Furniture")
+GameplayTagList=(Tag="Category.Deco.Lighting",DevComment="SubCategory Lighting")
+GameplayTagList=(Tag="Category.Defence",DevComment="Primary Category Defence")
+GameplayTagList=(Tag="Category.Defence.Turrets",DevComment="SubCategory Turrets")
+GameplayTagList=(Tag="Category.Defence.Barricades",DevComment="SubCategory Barricades")
+GameplayTagList=(Tag="Category.Infrastructure",DevComment="Primary Category Infrastructure")
+GameplayTagList=(Tag="Category.Infrastructure.Walls",DevComment="SubCategory Walls")
+GameplayTagList=(Tag="Category.Infrastructure.Floors",DevComment="SubCategory Floors")
+GameplayTagList=(Tag="Category.Infrastructure.Doors",DevComment="SubCategory Doors")
+GameplayTagList=(Tag="Category.Infrastructure.Roofs",DevComment="SubCategory Roofs")
+GameplayTagList=(Tag="Category.Stockage",DevComment="Primary Category Stockage")
+GameplayTagList=(Tag="Category.Stockage.Containers",DevComment="SubCategory Containers")
+GameplayTagList=(Tag="Category.Stockage.Chests",DevComment="SubCategory Chests")
